=== jonatjano/formulaire/07-desc.dtd
<!ELEMENT bibliotheque (editeur+)>
   <!ELEMENT editeur (serie+)>
	  <!ATTLIST editeur nom CDATA #REQUIRED >
	  <!ELEMENT serie (livre+)>
	     <!ATTLIST serie nom CDATA #REQUIRED >
	     <!ELEMENT livre (titre,((scenariste,dessinateur)|(dessinateur,scenariste)|auteur) )>
	        <!ELEMENT titre       (#PCDATA)>
	        <!ELEMENT scenariste  (#PCDATA)>
	        <!ELEMENT dessinateur (#PCDATA)>
	        <!ELEMENT auteur      (#PCDATA)>

=== jonatjano/formulaire/07-repertoire.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE bibliotheque SYSTEM "07-desc.dtd">

<bibliotheque>
	<editeur nom="Dargaud">
		<serie nom="Les aventures d'Astérix">
			<livre>
				<titre>Astérix le Gaulois</titre> 
				<scenariste>Goscinny</scenariste>
				<dessinateur>Uderzo</dessinateur>
			</livre>
			
			<livre>
				<titre>La serpe d'or</titre> 
				<scenariste>Goscinny</scenariste>
				<dessinateur>Uderzo</dessinateur>
			</livre>
			
			<livre>
				<titre>Le grand Fossé</titre> 
				<auteur>Uderzo</auteur>
			</livre>
		</serie>
		
		<serie nom="La complainte des landes perdues">
			<livre>
				<titre>Sioban</titre> 
				<scenariste>Rosinski</scenariste>
				<dessinateur>Dufaux</dessinateur>
			</livre>
			
			<livre>
				<titre>Blackmore</titre> 
				<scenariste>Rosinski</scenariste>
				<dessinateur>Dufaux</dessinateur>
			</livre>
		</serie>
	</editeur>
	
	<editeur nom="Delcourt">
		<serie nom="De cape et de crocs">
			<livre>
				<titre>Le secret du janissaire</titre> 
				<scenariste>Ayrolles</scenariste>
				<dessinateur>Masbou</dessinateur>
			</livre>
			
			<livre>
				<titre>Pavillon Noir!</titre> 
				<scenariste>Ayrolles</scenariste>
				<dessinateur>Masbou </dessinateur>
			</livre>
			
			<livre>
				<titre>L'arichel du Danger</titre> 
				<scenariste>Ayrolles</scenariste>
				<dessinateur>Masbou </dessinateur>
			</livre>
			
			<livre>
				<titre>Le mystère de l'ile étrange</titre> 
				<scenariste>Ayrolles</scenariste>
				<dessinateur>Masbou </dessinateur>
			</livre>
		</serie>
		
		<serie nom="garulfo">
			<livre>
				<titre>De mares en chateaux</titre> 
				<scenariste>Ayrolles</scenariste>
				<dessinateur>Maïorana </dessinateur>
			</livre>
			
			<livre>
				<titre>De mal en pis</titre> 
				<scenariste>Ayrolles</scenariste>
				<dessinateur>Maïorana </dessinateur>
			</livre>
		</serie>
		
		<serie nom="la graine de folie">
			<livre>
				<titre>Igguk</titre> 
				<auteur>Emmanuel Civiello</auteur>
			</livre>
			
			<livre>
				<titre>Le grand ornement</titre> 
				<auteur>Emmanuel Civiello</auteur>
			</livre>
			
			<livre>
				<titre>La Morrydwen</titre> 
				<auteur>Emmanuel Civiello</auteur>
			</livre>
			
			<livre>
				<titre>Le roy sans coeur</titre>
				<dessinateur>Emmanuel Civiello</dessinateur>
				<scenariste>Thomas Mosdi</scenariste>
			</livre>
		</serie>
		
		<serie nom="Petrus Barbygere">
			<livre>
				<titre>L'elficologue</titre>
				<scenariste>Pierre Dubois</scenariste>
				<dessinateur>Joann Sfar</dessinateur>
			</livre>
			
			<livre>
				<titre>Le croquemitaine d'écume</titre>
				<scenariste>Pierre Dubois</scenariste>
				<dessinateur>Joann Sfar</dessinateur>
			</livre>
		</serie>
		
		<serie nom="Les Potamoks">
			<livre>
				<titre>Terra Incognita</titre>
				<scenariste>Joann Sfar</scenariste>
				<dessinateur>Jose Luis Munuera</dessinateur>
			</livre>
			
			<livre>
				<titre>Les fontaines rouges</titre>
				<scenariste>Joann Sfar</scenariste>
				<dessinateur>Jose Luis Munuera</dessinateur>
			</livre>
			
			<livre>
				<titre>Nous et le désert</titre>
				<scenariste>Joann Sfar</scenariste>
				<dessinateur>Jose Luis Munuera</dessinateur>
			</livre>
		</serie>
	</editeur>
	
	<editeur nom="Vents d'ouest">
		<serie nom="Fol">
			<livre>
				<titre>Fol</titre> 
				<auteur>Prugne Patrick</auteur>
			</livre>
			
			<livre>
				<titre>Le temps du rübezhal</titre> 
				<auteur>Prugne Patrick</auteur>
			</livre>
		</serie>
	</editeur>
</bibliotheque>
